stages:
  data_validation:
    cmd: python src/data_validation.py
    deps:
      - data/loan_data.csv

  clean_data:
    cmd: python src/data_cleaning.py
    deps:
      - data/loan_data.csv
    outs:
      - data/processed/cleaned_data.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - data/processed/cleaned_data.csv
    outs:
      - data/processed/featured_data.csv

  train_model:
    cmd: python src/train_model.py
    deps:
      - data/processed/featured_data.csv
    outs:
      - models/model.pkl
